version: "3.9"

services:
  si-datagpt-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: si-datagpt-ui:latest
    container_name: si-datagpt-ui
    ports:
      - "9797:9797"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    image: si-datagpt-ui:latest
    container_name: si-datagpt-ui
    ports:
      - "9797:9797"
    restart: unless-stopped